#!/bin/sh
FG='#aaaaaa'
BG='#111111'
WIDTH=`xrandr | grep "*"`
#FONT='-*-terminus-*-r-normal-*-*-120-*-*-*-*-iso8859-*'

conky | dzen2 -e - -h '20' -w 1920 -ta l -fg $FG -bg $BG -fn 'Dejavu Sans Mono' -x 0 -y 0
